#define RES_CLIENT               256

#define MI_MORECARS              320
#define MI_LESSCARS              321

#define BMP_ROAD                 256
#define BMP_RCL                  257
#define BMP_BCL                  258
#define BMP_GCL                  259
#define BMP_RTL                  260
#define BMP_BTL                  261
#define BMP_RCR                  262
#define BMP_BCR                  263
#define BMP_GCR                  264
#define BMP_RTR                  265
#define BMP_BTR                  266
